In [1]:
#numpy基础属性

import numpy as np

array  = np.array([[1,2,3],[2,3,4]])

print(array)

#维数，形状-几行几列，大小
print(array.ndim, array.shape, array.size)


[[1 2 3]
 [2 3 4]]
2 (2, 3) 6


In [2]:
a = np.array([2,23,4],dtype=np.float32) #类型精确 可以减小内存占用
print(a.dtype)

float32


In [3]:
a = np.zeros((3,4))
print(a, a.dtype)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] float64


In [4]:
a = np.ones((3,4), dtype=np.int16)
print(a, a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int16


In [5]:
a = np.empty((3,4))
print(a, a.dtype)

[[  0.00000000e+000   4.94065646e-324   9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323   3.45845952e-323]
 [  3.95252517e-323   4.44659081e-323   4.94065646e-323   5.43472210e-323]] float64


In [6]:
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [7]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.linspace(1,20,20).reshape((4,5)) #等间距
print(a)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]]


In [21]:
#基本的运算
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
c = a**2*np.sin(a)
print(c)

print(a < 25)

[10 20 30 40] [0 1 2 3]
[  -54.40211109   365.17810029  -889.22846168  1192.18105677]
[ True  True False False]


In [33]:
a = np.array([[1,1],[0,1]])

b = np.arange(4).reshape((2,2))

print(a,b)

print(a*b) #逐个相乘

print( np.dot(a,b)) #矩阵乘法
print(a.dot(b))

[[1 1]
 [0 1]] [[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [44]:
a = np.random.random((2,4))
print(a)

print(np.sum(a,axis=1))
print(np.min(a,axis=0))

[[ 0.20839958  0.7482558   0.27886012  0.64145282]
 [ 0.52796709  0.8618956   0.04443993  0.51296277]]
[ 1.87696833  1.94726538]
[ 0.20839958  0.7482558   0.04443993  0.51296277]


In [69]:
a = np.arange(2,14).reshape((3,4))
print(a)

print( np.argmin(a) ) #最小值索引
print( np.argmax(a)) 


print(np.mean(a), a.mean()) #平均值
print(np.mean(a,axis=0))

print(np.average(a)) 
print( np.median(a)) #中位数
print( np.cumsum(a)) # 累加 2  2+3 2+3+4 2+3+4+5 
print( np.diff(a)) # 累差 3-2 4-3 5-4

a[2][3]=0
print(np.nonzero(a)) #输出非零

print(a)

print(np.sort(a)) #排序


print(np.transpose(a)) #矩阵转置

print(a.T.dot(a))

print(np.clip(a,5,9)) #所有小于5的 变为5  大于9的 变为9

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5 7.5
[ 6.  7.  8.  9.]
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2]))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12  0]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [ 0 10 11 12]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9  0]]
[[140 158 176  64]
 [158 179 200  78]
 [176 200 224  92]
 [ 64  78  92 106]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 5]]


In [79]:
#numpy索引
a = np.arange(3,15).reshape((3,4))
print(a)
print(a[2][1])
print(a[2,1])
print(a[2,:])
print(a[:,1])

for row in a: #行
    print(row)

for column in a.T: #列
    print(column)
    
for item in a.flat: #单个元素
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
12
[11 12 13 14]
[ 4  8 12]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [91]:
a = np.array([1,1,1])
b = np.array([2,2,2])

print(np.vstack((a,b))) #行合并
print(np.hstack((a,b))) #列合并

print(a[:,np.newaxis].shape) #增加一个维度


c = np.concatenate((a,b,b),axis=0)  #指定维度的合并
print(c)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3, 1)
[1 1 1 2 2 2 2 2 2]


In [99]:
a = np.arange(12).reshape((3,4))
print(a)

print(np.split(a,2,axis=1))

print(np.array_split(a,3,axis=1)) 

print(np.vsplit(a,3))
print(np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [105]:
a = np.arange(4)
print(a)

b = a

a[0]=11

b is a

print(b)


d = a.copy()

a[0]=0

print(a)
print(d)



[0 1 2 3]
[11  1  2  3]
[0 1 2 3]
[11  1  2  3]
