In [1]:
import numpy as np

data_file = "affinity_dataset.txt"

x = np.loadtxt(data_file)

In [2]:
print(x[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]
